//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.TravelParts {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblTravelId;
	protected global::System.Web.UI.WebControls.Label lblUserId;
	protected global::System.Web.UI.WebControls.Label lblPartType;
	protected global::System.Web.UI.WebControls.Label lblDescription;
	protected global::System.Web.UI.WebControls.Label lblPartUrl;
	protected global::System.Web.UI.WebControls.Label lblLongitude;
	protected global::System.Web.UI.WebControls.Label lblLatitude;
	protected global::System.Web.UI.WebControls.Label lblHeight;
	protected global::System.Web.UI.WebControls.Label lblArea;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;
	protected global::System.Web.UI.WebControls.Label lblIsDelete;


       
    }
}
