//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.User {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblUserName;
	protected global::System.Web.UI.WebControls.Label lblShowName;
	protected global::System.Web.UI.WebControls.Label lblPassWord;
	protected global::System.Web.UI.WebControls.Label lblSex;
	protected global::System.Web.UI.WebControls.Label lblPhoneNum;
	protected global::System.Web.UI.WebControls.Label lblEmail;
	protected global::System.Web.UI.WebControls.Label lblAge;
	protected global::System.Web.UI.WebControls.Label lblImgUrl;
	protected global::System.Web.UI.WebControls.Label lblIsEnable;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;
	protected global::System.Web.UI.WebControls.Label lblUpdateTime;


       
    }
}
